import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import NavigationBar from "@/components/navbar";

const DynamicNavbar = dynamic(() => import("@/components/navbar"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
          <NavigationBar />
        <div className="md:container md:mx-auto">
          {/* <DynamicNavbar /> */}
          {children}
        </div>
      </body>
    </html>
  );
}
